apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:  
  labels:
    release: prometheus-release
  name: vietdevops-metric-servicemonitor
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
    interval: 15s
    scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app: vietdevops-metric-app-service

